- name: Configure a slave Jenkins
  hosts: deployment
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: false
  tasks:
  - name: updating all packages 
    apt:
      update_cache: yes
  - name: installing docker 
    apt: 
      name: docker
      state: latest
  - name: installing Java
    apt:
      name: openjdk-8-jdk 
      state: present
  - name: Starting docker service
    service:
      name: docker
      state: started
      enabled: yes
  - name: create slave directory
    file:
      path: /home/ubuntu/jenkins_home
      state: directory
      mode:   0777
  - name: Adding the ubuntu to the docker group
    user:
      name: ubuntu
      groups: docker
      append: yes
  - name: Creating bin directory 
    file: 
      path: /home/ubuntu/bin
      state: directory
      mode: 0777
  - name: copying the agent jar to the slave 
    copy:
      src:  agent.jar
      dest: /home/ubuntu/bin/agent.jar
  - name: install git 
    apt:
      name: git
      state: latest